### ISSUE TITLE
Linux stock puppet agent detection broken in Release v0.7.1

### ISSUE THREAD

**Issue by svenbs** [jpogran/puppet-vscode#164] opened 2017-10-06 07:34 UTC
Hi,

first of all thanks for the great work. I really like this plugin and am using it for quite some time now.

But this recent change (https://github.com/jpogran/puppet-vscode/commit/9b954d847be456babcc66e9e1fe1df06db64cea7#commitcomment-24780246) sadly broke my current installation of puppet-vscode.
It leads to problems on Ubuntu 17.04 with a stock puppet installation. It cannot find any VERSION file, cause there is no /opt/puppetlabs/puppet directory and with stock puppet there a VERSION file is not installed.

Maybe it would be better to ask the puppet binary via "puppet agent --version" for it's version and truly determine if this is a valid agent installation. Although it seems to me this code is not really depending on a specific version.

Kind Regards,
Sven

**Comment by glennsarti** [comment] 2017-10-06 15:37
Hi @svenbs Thankyou for the bug report.  I'm just trying to reproduce your issue and I'm having an issue.  Admittedly I am running Ubuntu 16.04 not 17.04, but using the instructions from puppet on how to install the agent appears to work.

Are you able to give me instructions on how you installed puppet-agent on Ubuntu?  and also the agent version.

**Comment by svenbs** [comment] 2017-10-10 15:56
Hi @glennsarti, sorry i've kept you waiting for so long.

This should be working with Ubuntu 16.04 as well. You have to install puppet from the ubuntu stock repository not the apt-Repos from puppetlabs. Just install ubuntu clean and do "apt install puppet".

That would be the same for stock CentOS/RedHat (I believe it's from the epel repos) via "yum install puppet". This would lead to the same problem as the stock repo installs binaries to /usr/bin

**Comment by glennsarti** [comment] 2017-10-13 17:19
Thanks.  I wonder what version of Puppet that is.  I will try it out.

**Comment by glennsarti** [comment] 2017-10-13 18:10
Ok, so looks like it installs Puppet version 3.8.5 which is end of life.

**Comment by jpogran** [comment] 2017-10-19 17:09
Closing as this is due to the EOL Puppet version, not the extensions

**Closed by jpogran** 2017-10-19 17:09 UTC
Labels: bug, lang-server
