### ISSUE TITLE
Puppet Extension DDOS the System => 90% Cpu / VsCode 2.6GB Ram / 80% disk bandwith

### ISSUE THREAD

**Issue by tebeco** [jpogran/puppet-vscode#220] opened 2018-02-21 08:30 UTC
### What Versions are you running?

OS Version: `Win 10`
VSCode Version: `1.20.1`
Puppet Extension Version: `0.9.0`
Puppet Agent Version: `5.4.0`
PDK Version (if applicable): `1.3.2`

### What You Are Seeing?
Puppet Extension does not load (not always at the same step):
* Stuck on starting
* Stuck on some percentage

### What is Expected?
puppet extension should use extension settings even if ran locally, like the Port to use for the Lang Server

### How Did You Get This To Happen? (Steps to Reproduce)
On a Win10 computer with UAC + Firewall active (so not admin)
I can open elevated terminal with almost all admin right, so i can authorize some port to be open :
`> netsh http add urlacl url="http://+:8081/" user=everyone`
No software can listen on a port unless i do stuff like that
I hope the Langage server is exposed using HTTP (so far i read TCP everywhere but can't confirm that this is or not HTTP on top)

I tried to specified puppet extension settings like :
```
    "puppet.puppetAgentDir": "C:\\Program Files\\Puppet Labs\\Puppet",
    "puppet.languageserver.address": "127.0.0.1",
    "puppet.languageserver.port": 8081,
    "puppet.languageserver.timeout": 1000,
```

I'm not sure if this settings is used for that [Listen(0)](https://github.com/jpogran/puppet-vscode/blob/009e5bf64556e451fd44b61c75c986e67e4b16eb/client/src/connection.ts#L213)
but this specific `Listen(0)` feels like the root cause of the folowwing logs :

### Output Log
The last lines of the Logs are just overflowing with about 1000 tries per SECONDS so i let you guess how devastating it is ^^.
Could we add :
* A port parameter that is used instead of 0, 0 by default is fine
* A delay between retry
* A max attempt count
* An actual UI Warning then Error message when it cannot bind a port

```
[Extension Host] DEBUG: 2018-02-19T11:56:40.215Z Stopping...
console.ts:123 [Extension Host] DEBUG: 2018-02-19T11:56:40.215Z Stopped
console.ts:123 [Extension Host] Starting Puppet...
console.ts:123 [Extension Host] DEBUG: 2018-02-19T11:56:40.215Z [createLanguageServerProcess] Language server found at: C:\Users\foobar\.vscode\extensions\jpogran.puppet-vscode-0.9.0\vendor\languageserver\puppet-languageserver
console.ts:123 [Extension Host] DEBUG: 2018-02-19T11:56:40.215Z [getRubyExecFromPuppetAgent] Using environment variable RUBY_DIR=C:\Program Files\Puppet Labs\Puppet\sys\ruby
console.ts:123 [Extension Host] DEBUG: 2018-02-19T11:56:40.215Z [getRubyExecFromPuppetAgent] Using environment variable PATH=C:\Program Files\Puppet Labs\Puppet\puppet\bin;C:\Program Files\Puppet Labs\Puppet\facter\bin;C:\Program Files\Puppet Labs\Puppet\hiera\bin;C:\Program Files\Puppet Labs\Puppet\mcollective\bin;C:\Program Files\Puppet Labs\Puppet\bin;C:\Program Files\Puppet Labs\Puppet\sys\ruby\bin;C:\Program Files\Puppet Labs\Puppet\sys\tools\bin;C:\Program Files\Puppet Labs\Puppet\puppet\bin;C:\Program Files\Puppet Labs\Puppet\facter\bin;C:\Program Files\Puppet Labs\Puppet\hiera\bin;C:\Program Files\Puppet Labs\Puppet\mcollective\bin;C:\Program Files\Puppet Labs\Puppet\bin;C:\Program Files\Puppet Labs\Puppet\sys\ruby\bin;C:\Program Files\Puppet Labs\Puppet\sys\tools\bin;C:\Program Files\Docker\Docker\Resources\bin;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\dotnet\;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Puppet Labs\Puppet\bin;C:\Program Files\Puppet Labs\DevelopmentKit\private\ruby\2.1.9\bin;C:\Program Files\Microsoft VS Code Insiders\bin;C:\Program Files\Java\jdk1.8.0_151;C:\Users\ahertogs031416\AppData\Roaming\npm;C:\Program Files\Microsoft VS Code\bin
console.ts:123 [Extension Host] DEBUG: 2018-02-19T11:56:40.216Z [getRubyExecFromPuppetAgent] Using environment variable RUBYLIB=C:/Program Files/Puppet Labs/Puppet/puppet/lib;C:/Program Files/Puppet Labs/Puppet/facter/lib;C:/Program Files/Puppet Labs/Puppet/hiera/lib;C:/Program Files/Puppet Labs/Puppet/mcollective/lib;C:/Program Files/Puppet Labs/Puppet/puppet/lib;C:/Program Files/Puppet Labs/Puppet/facter/lib;C:/Program Files/Puppet Labs/Puppet/hiera/lib;C:/Program Files/Puppet Labs/Puppet/mcollective/lib;
console.ts:123 [Extension Host] DEBUG: 2018-02-19T11:56:40.216Z [getRubyExecFromPuppetAgent] Using environment variable RUBYOPT=rubygems
console.ts:123 [Extension Host] DEBUG: 2018-02-19T11:56:40.216Z [getRubyExecFromPuppetAgent] Using environment variable SSL_CERT_FILE=C:\Program Files\Puppet Labs\Puppet\puppet\ssl\cert.pem
console.ts:123 [Extension Host] DEBUG: 2018-02-19T11:56:40.216Z [getRubyExecFromPuppetAgent] Using environment variable SSL_CERT_DIR=C:\Program Files\Puppet Labs\Puppet\puppet\ssl\certs
console.ts:123 [Extension Host] DEBUG: 2018-02-19T11:56:40.216Z [createLanguageServerProcess] Creating server process to identify random port
console.ts:123 [Extension Host] DEBUG: 2018-02-19T11:56:40.217Z [createLanguageServerProcess] Selected port for local language server: 1077
console.ts:123 [Extension Host] DEBUG: 2018-02-19T11:56:40.217Z [createLanguageServerProcess] Server process to identify random port disconnected
console.ts:123 [Extension Host] DEBUG: 2018-02-19T11:56:40.217Z Starting the language server with ruby C:\Users\foobar\.vscode\extensions\jpogran.puppet-vscode-0.9.0\vendor\languageserver\puppet-languageserver --ip=127.0.0.1 --port=1077 --timeout=1000
console.ts:123 [Extension Host] DEBUG: 2018-02-19T11:56:40.223Z Language server PID:1560
console.ts:123 [Extension Host] DEBUG: 2018-02-19T11:56:40.223Z LanguageServer Process Started: [object Object]
console.ts:123 [Extension Host] DEBUG: 2018-02-19T11:56:40.223Z Congratulations, your extension "vscode-puppet" is now active!
console.ts:123 [Extension Host] DEBUG: 2018-02-19T11:56:42.811Z OUTPUT: LANGUAGE SERVER RUNNING 127.0.0.1:1077
console.ts:123 [Extension Host] DEBUG: 2018-02-19T11:56:42.811Z Configuring language server options
console.ts:123 [Extension Host] DEBUG: 2018-02-19T11:56:42.811Z Configuring language server client options
console.ts:123 [Extension Host] DEBUG: 2018-02-19T11:56:42.811Z Starting language server client (host 127.0.0.1 port 1077)
console.ts:123 [Extension Host] DEBUG: 2018-02-19T11:56:42.864Z Language server client started, setting puppet version
console.ts:123 [Extension Host] Loading Puppet
console.ts:123 [Extension Host] ERROR: 2018-02-19T11:56:43.055Z [Puppet Lang Server Client] Error: read ECONNRESET
console.ts:123 [Extension Host] Starting Error
console.ts:123 [Extension Host] ERROR: 2018-02-19T11:56:43.056Z [Puppet Lang Server Client] Error: This socket is closed
console.ts:123 [Extension Host] Starting Error
console.ts:123 [Extension Host] ERROR: 2018-02-19T11:56:43.056Z [Puppet Lang Server Client] Error: This socket is closed
console.ts:123 [Extension Host] Starting Error
console.ts:123 [Extension Host] ERROR: 2018-02-19T11:56:43.057Z [Puppet Lang Server Client] Error: This socket is closed
console.ts:123 [Extension Host] Starting Error
console.ts:123 [Extension Host] ERROR: 2018-02-19T11:56:43.057Z [Puppet Lang Server Client] Error: This socket is closed
console.ts:123 [Extension Host] Starting Error
console.ts:123 [Extension Host] ERROR: 2018-02-19T11:56:43.057Z [Puppet Lang Server Client] Error: This socket is closed
console.ts:123 [Extension Host] Starting Error
```

**Comment by glennsarti** [comment] 2018-02-21 08:48
Thanks @tebeco .  I can definitely look at why this is failing.  Looks like it could be VSCode trying to start the language server as opposed the server itself.  But that gives me a great starting point.

Odd that it's trying a different port than the one you specified in the config settings... something else to look at.

For ref. The transport is TCP although you can run the language server over STDIO.  The protocol is JSONRPC (https://microsoft.github.io/language-server-protocol/specification) so it _looks_ HTTP-ish but it's not.

**Comment by tebeco** [comment] 2018-02-21 08:52
so the `netsh http ....` wont work i guess :s ?

`Odd that it's trying a different port than the one you specified in the config settings... something else to look at.`
Well looking at :
https://github.com/jpogran/puppet-vscode/blob/009e5bf64556e451fd44b61c75c986e67e4b16eb/client/src/connection.ts#L213

It ignore the settings right ? it listen on a random port then override what's in the settings

**Comment by glennsarti** [comment] 2018-02-21 08:52
The `listen(0)` trick is just used to find a local unused port.  Note in your logs it selects 1077.

I suspect it's a firewall issue and the client is just continuously trying to reconnect.

**Comment by glennsarti** [comment] 2018-02-21 08:52
Looks like we don't check for the a static port in that code :-(

**Comment by tebeco** [comment] 2018-02-21 08:53
`let listenPort = connMgr.connectionConfiguration.port === undefined ? 0 : connMgr.connectionConfiguration.port;`

**Comment by glennsarti** [comment] 2018-02-21 08:55
Well, the good news I think I can see where the problem is.  Or more correctly, multiple problems.

As a workaround, you'd need to add a firewall exception for VSCode (code.exe).

**Comment by glennsarti** [comment] 2018-02-21 08:56
We definitely need 3 of your suggestions too.

* A delay between retry
* A max attempt count
* An actual UI Warning then Error message when it cannot bind a port

**Comment by tebeco** [comment] 2018-02-21 10:37
* Just tried Exception for "code" and "code-insiders" executable
* Same for "Inbound rules"
* Even tried running VsCode as Admin
Still got the same behavior.

As long as i cannot predict the TCP port used, i cannot create TCP rules based on port number :s

**Comment by glennsarti** [comment] 2018-02-21 11:15
We'll try and get this fixed for next release.

**Comment by glennsarti** [comment] 2018-03-21 03:02
Splitting this out into several issues;

#238 - Using STDIO instead of TCP for the local lang server bypasses all of these issues
#239 - Use TCP transport if either port or host is specified
#240 - TCP Lang client should have reasonable retry defaults
#241 - If a port is specified use that instead of finding a random one

**Comment by glennsarti** [comment] 2018-03-21 03:03
Closing this issue and the resolutions for each of this new issues can be tracked and worked on independently.

Feel free to reopen if you would like to pursue this further.

**Closed by glennsarti** 2018-03-21 03:03 UTC
Labels: bug, extension, lang-server
